### This function returns lyrics ranking generated by KNN Regression

library(FNN)

knn_reg <- function (X, Y, X_pre, K=1500, algo="kd_tree") {
  
  freq.matrix <- NULL
  
  for (i in 1:ncol(Y)) {
    knnModel <- knn.reg(X, test = X_pre,y = Y[,i], k=K, algorithm=algo)
    freq.matrix <- cbind(freq.matrix, knnModel$pred)
  }
  
  rank.matrix <- t(apply(-freq.matrix, 1, rank, ties.method='last')) #'last' was tested to be better than 'first'
  rank.df <- data.frame(rank.matrix)
  names(rank.df) <- names(Y)
  return(rank.df)
  
} 