### This function returns lyrics ranking generated by Linear Regression 

linear_reg <- function(X, Y, X_pre){
  
  freq.matrix <- NULL

  for (i in 1:ncol(Y)) {
    lm.df <- data.frame(Y[,i],X)
    lm1 <- lm(formula(lm.df), data=lm.df)
    lm_pre <- predict(lm1, X_pre) 
    freq.matrix <- cbind(freq.matrix, lm_pre)
  }
  
  rank.matrix <- t(apply(-freq.matrix, 1, rank, ties.method='last'))
  rank.df <- data.frame(rank.matrix)
  names(rank.df) <- names(Y)
  return(rank.df)
  
}