### This function returns lyrics ranking generated by Logistic Regression

logit_reg <- function(X, Y, X_pre){
  
  Y_binary <- as.matrix((Y > 0) + 0)
  freq.matrix <- NULL
  
  for (i in 1:ncol(Y_binary)) {
    lm.df <- data.frame(Y_binary[,i],X)
    lm1 <- glm(formula(lm.df), family = binomial(), data=lm.df)
    lm_pre <- predict(lm1, X_pre, type = "response" ) 
    freq.matrix <- cbind(freq.matrix, lm_pre)*10000
  }
  
  rank.matrix <- t(apply(-freq.matrix, 1, rank, ties.method='last'))
  rank.df <- data.frame(rank.matrix)
  names(rank.df) <- names(Y_binary)
  return(rank.df)
}