### This function returns lyrics ranking generated by Random Forest 

library(randomForest)

random_forest <- function(X, Y, X_pre)

num_test<-100
Y<-Y[,-which(colSums(Y)==0)]
Y <- as.matrix((Y > 0) + 0)
freq.matrix <- NULL

for (i in 1:ncol(Y)) {
  fit <- randomForest(X, as.factor(Y[,i]), importance=T, ntree=200)
  pre <- predict(fit, X_pre, type = "vote")[,2]
  freq.matrix <- cbind(freq.matrix, pre)
}

rank.matrix <- t(apply(-freq.matrix, 1, rank, ties.method='last'))
rank.df <- data.frame(rank.matrix)
names(rank.df) <- names(Y)

return(rank.df)